import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'HUSH Timer - Privacy Policy',
  description: 'Privacy Policy for HUSH Timer',
};

export default function PrivacyPolicyPage() {
  const lastUpdated = 'October 24, 2025';

  return (
    <div className="text-foreground mx-auto max-w-4xl px-4 py-8 leading-relaxed">
      <h1 className="mb-4 text-3xl font-bold">Privacy Policy</h1>
      <p className="text-muted-foreground mb-6 italic">Last updated: {lastUpdated}</p>

      <section className="mb-8">
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and
          disclosure of Your information when You use the Service and tells You about Your privacy
          rights and how the law protects You.
        </p>
        <p className="mb-4">
          We use Your Personal data to provide and improve the Service. By using the Service, You
          agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      <hr className="border-border my-8" />

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Interpretation and Definitions</h2>

      <h3 className="mt-6 mb-3 text-xl font-medium">Interpretation</h3>
      <p className="mb-4">
        The words whose initial letters are capitalized have meanings defined under the following
        conditions. The following definitions shall have the same meaning regardless of whether they
        appear in singular or in plural.
      </p>

      <h3 className="mt-6 mb-3 text-xl font-medium">Definitions</h3>
      <ul className="mb-6 list-disc space-y-3 pl-6">
        <li>
          <strong>Account:</strong> A unique account created for You to access our Service or parts
          of our Service.
        </li>
        <li>
          <strong>Application:</strong> Refers to HushTimer, the software program provided by the
          Company.
        </li>
        <li>
          <strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our")
          refers to HushTimer, Taiwan.
        </li>
        <li>
          <strong>Personal Data:</strong> Any information that relates to an identified or
          identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> Refers to the Application.
        </li>
        <li>
          <strong>Usage Data:</strong> Data collected automatically, either generated by the use of
          the Service or from the Service infrastructure itself.
        </li>
      </ul>

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Collecting and Using Your Personal Data</h2>

      <h3 className="mt-6 mb-3 text-xl font-medium">Types of Data Collected</h3>
      <h4 className="mt-4 mb-2 text-lg font-semibold">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain personally identifiable
        information including:
      </p>
      <ul className="mb-6 list-disc pl-6">
        <li>Email address</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="mt-4 mb-2 text-lg font-semibold">Usage Data</h4>
      <p className="mb-4">
        Usage Data is collected automatically and may include Your Device&apos;s IP address, browser
        type, pages visited, time spent, and unique device identifiers.
      </p>

      <h3 className="mt-6 mb-3 text-xl font-medium">Use of Your Personal Data</h3>
      <p className="mb-4">The Company may use Personal Data for purposes including:</p>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>To provide and maintain our Service.</li>
        <li>To manage Your Account and registration.</li>
        <li>To contact You regarding updates or informative communications.</li>
        <li>For the performance of a contract.</li>
        <li>To manage Your requests.</li>
      </ul>

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Retention and Deletion</h2>
      <p className="mb-4">
        The Company will retain Your Personal Data only for as long as is necessary for the purposes
        set out in this Privacy Policy. You have the right to delete or request that We assist in
        deleting the Personal Data that We have collected about You.
      </p>

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Children's Privacy</h2>
      <p className="mb-4">
        Our Service does not address anyone under the age of 13. We do not knowingly collect
        personally identifiable information from anyone under the age of 13.
      </p>

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Security of Your Personal Data</h2>
      <p className="mb-4">
        The security of Your Personal Data is important to Us, but remember that no method of
        transmission over the Internet is 100% secure. While We strive to use commercially
        reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
      </p>

      <h2 className="mt-8 mb-4 text-2xl font-semibold">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="mb-8 list-disc pl-6">
        <li>
          By email:{' '}
          <a href="mailto:ricky9667@gmail.com" className="text-primary hover:underline">
            ricky9667@gmail.com
          </a>
        </li>
      </ul>
    </div>
  );
}
